<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brochure</name>
   <tag></tag>
   <elementGuidId>03355930-5754-49ce-81cb-8fa2402b69d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Resources']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27d41793-1aec-4b59-b2e5-7f5b920f6e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://spochub.com/downlaod?file_type=process_doc&amp;file_name=2_1633512426.pdf&amp;prod_name=enlight-web-vpn</value>
      <webElementGuid>6e10400c-de24-4cb9-9f6e-d11b695a5a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brochure</value>
      <webElementGuid>9234442b-d916-43dc-9235-35d0540d7935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Resources&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;sh-overview-detail&quot;]/div[@class=&quot;sh-tags-btns&quot;]/a[2]</value>
      <webElementGuid>a70da7bd-e082-47bf-9217-2b7284f4eb68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Resources']/div/div/div/a[2]</value>
      <webElementGuid>16b25e46-5005-4ca4-ae19-d5c9d1a2d3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brochure')]</value>
      <webElementGuid>1476c225-1031-4a4c-ad4c-39c97ed987e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data-sheet'])[1]/following::a[1]</value>
      <webElementGuid>022c7298-99ac-432a-b5e2-41a5f38c792a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Documentation'])[1]/following::a[2]</value>
      <webElementGuid>c553f8a2-eca2-43c4-a4b9-e719dbfe2a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Study'])[2]/preceding::a[1]</value>
      <webElementGuid>73d40fed-8fd4-4133-b23b-72d26c5c9c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Manual'])[1]/preceding::a[2]</value>
      <webElementGuid>a3ec4991-05c1-4f84-975b-0a842e36f4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brochure']/parent::*</value>
      <webElementGuid>e122bee8-dc6f-4ef8-9382-9f01b9d7883c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://spochub.com/downlaod?file_type=process_doc&amp;file_name=2_1633512426.pdf&amp;prod_name=enlight-web-vpn')]</value>
      <webElementGuid>58657147-6101-44ea-b3bc-052f6f1275df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a[2]</value>
      <webElementGuid>c251ee30-707e-46e7-8f3b-26b2e60ebf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://spochub.com/downlaod?file_type=process_doc&amp;file_name=2_1633512426.pdf&amp;prod_name=enlight-web-vpn' and (text() = 'Brochure' or . = 'Brochure')]</value>
      <webElementGuid>08238fff-6be1-441d-9d1f-9fa06ba7c0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
